allprojects {
    repositories {
        mavenCentral()
    }
    group = 'nkp.pspValidator'
    version = findProperty('appVersion') ?: '0.0.0'
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17) // Fixed to Java 17 for compilation. Java 21 for runtime
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    dependencies {
        //testImplementation 'junit:junit:4.13.1'
    }
}

