plugins {
    id 'java'
    //id 'application'
}

// Create a JAR task
jar {
    manifest {
        attributes('Main-Class': 'nkp.pspValidator.cli.Main')
    }
    // Include all dependencies into the JAR (optional, depends on your use case)
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    archiveFileName = "cliModule-${project.version}.jar"
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation project(':modules:sharedModule')
    implementation 'commons-cli:commons-cli:1.3.1'
}

tasks.register('run', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
}

tasks.register('runHelp', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--help']
}

tasks.register('runVersion', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--version']
}

tasks.register('runDev', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--action', "DEV"]
}


def homeDir = System.getProperty("user.home")

tasks.register('runDevMrMinify', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--action', "BUILD_MINIFIED_PACKAGE",
            '--psp', "${homeDir}/TrineraProjects/Validator/komplexni-validator/modules/sharedModule/src/test/resources/monograph_1.2/b50eb6b0-f0a4-11e3-b72e-005056827e52",
            '--minified-psp-dir', "${homeDir}/TrineraProjects/Validator/tmp/komplexni-validator",
    ]
}

tasks.register('runDevMrValidate', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--action', "VALIDATE_PSP"
            //, '--psp', "${homeDir}/TrineraProjects/Validator/komplexni-validator/modules/sharedModule/src/test/resources/data_disc_0.1/osa001-00117i"
            , '--psp', "${homeDir}/TrineraProjects/Validator/tmp/komplexni-validator/b50eb6b0-f0a4-11e3-b72e-005056827e52_minified"
            //, '--psp', "${homeDir}/TrineraProjects/KramarskeTisky/data/input/sample1/input/tmp/_ndk-package/2610798805-2025_02_18-17_21_12,336/d7742610-73d6-476f-84af-c15a7156c5a6"
            , '--config-dir', "${homeDir}/TrineraProjects/Validator/komplexni-validator/modules/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig"
            , '--forced-dmf-mon-version', '2.1'
            , '--forced-dmf-dad-version', '0.1'
            , '--preferred-dmf-dad-version', '0.1'
            , '--disable-imagemagick'
            , '--disable-imagemagick'
            , '--disable-imagemagick'
            , '--disable-kakadu'
            , '--disable-mp3val'
            , '--disable-shntool'
            , '--disable-checkmate'
    ]
}

tasks.register('runDevMrValidateProfile', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('nkp.pspValidator.cli.Main')
    args = ['--action', "VALIDATE_METADATA_BY_PROFILE",
            '--config-dir', "${homeDir}/TrineraProjects/Validator/komplexni-validator/modules/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig",
            //'--metadata-profile-id', 'monograph_1.4', //Chybí typ profilu (fDmf=monograph_1.4)
            //'--metadata-profile-id', 'monograph_1.4:blbost', //Neznámý typ profilu: blbost (fDmf=monograph_1.4)
            //'--metadata-profile-id', 'monograph_1.4:biblio', //Chybí metadatový formát (fDmf=monograph_1.4, typ=biblio)
            //'--metadata-profile-id', 'monograph_1.4:biblio:blbost', //Neznámý metadatový formát: blbost (fDmf=monograph_1.4, typ=biblio)
            //'--metadata-profile-id', 'monograph_1.4:biblio:mods', //Chybí název profilu (fDmf=monograph_1.4, typ=biblio, formát=mods)
            //'--metadata-profile-id', 'monograph_1.4:biblio:mods:blbost', //Soubor profilu neexistuje: blbost.xml (fDmf=monograph_1.4, typ=biblio, formát=mods)
            //'--metadata-profile-id', 'monograph_1.4:tech', //Chybí název profilu (fDmf=monograph_1.4, typ=tech)
            //'--metadata-profile-id', 'monograph_1.4:tech:blbost', //Soubor profilu neexistuje: blbost.xml (fDmf=monograph_1.4, typ=tech)
            '--metadata-profile-id', 'monograph_1.4:biblio:mods:page_rda',
            '--metadata-file', "${homeDir}/TrineraProjects/Validator/komplexni-validator/modules/sharedModule/src/test/resources/metadata_only/mon_1.4/mods_page_rda.xml"
    ]
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

//build - vyrobi  modules/cliModule/build/libs/cliModule-VERZE.jar
//./gradlew :modules:cliModule:jar

//run - spusti nkp.pspValidator.cli.Main.main()
//./gradlew :modules:cliModule:run

//runHelp - spusti nkp.pspValidator.shared.Main.main("--help")
//./gradlew :modules:cliModule:runHelp

//runVersion - spusti nkp.pspValidator.shared.Main.main("--version")
//./gradlew :modules:cliModule:runVersion

//runDev - spusti nkp.pspValidator.shared.Main.main("--action DEV")
//./gradlew :modules:cliModule:runDev

//runDevValidate -spusti CLI s akci VALIDATE_PSP a hardcoded parametry
//./gradlew :modules:cliModule:runDevValidate


//hardcoded for Martin Řehánek
//============================

//runDevMrMinify - spusti CLI s akci BUILD_MINIFIED_PACKAGE a hardcoded parametry
//./gradlew :modules:cliModule:runDevMrMinify

//runDevMrValidateProfile - spusti CLI s akci VALIDATE_METADATA_BY_PROFILE a hardcoded parametry
//./gradlew :modules:cliModule:runDevMrValidateProfile

//runDevMrValidate - spusti CLI s akci VALIDATE_PSP a hardcoded parametry
//./gradlew :modules:cliModule:runDevMrValidate
